-- PRAGMA foreign_keys=OFF;
BEGIN;
CREATE TABLE USER ( USERNAME   TEXT  PRIMARY KEY,
                    HASDEDPW   TEXT  NOT NULL);

CREATE TABLE BLOG ( BLOGNAME   TEXT  PRIMARY KEY,
                    OWNER      TEXT  NOT NULL,
                    FOREIGN KEY(OWNER) REFERENCES USER(USERNAME));

CREATE TABLE POST ( POSTID     INTEGER   PRIMARY KEY   AUTOINCREMENT,
                    TITLE      TEXT      NOT NULL,
                    CONTENT    TEXT      NOT NULL,
                    POSTDATE   DATE      NOT NULL,
                    BLOGNAME   TEXT      NOT NULL,
                    FOREIGN KEY(BLOGNAME) REFERENCES BLOG(BLOGNAME));

CREATE TABLE LAYOUT( LAYOUTID   INTEGER   PRIMARY KEY   AUTOINCREMENT,
                     BLOGNAME   TEXT      NOT NULL,
                     FOREIGN KEY(BLOGNAME) REFERENCES BLOG(BLOGNAME));

CREATE TABLE MESSAGE( MSGID     INTEGER   PRIMARY KEY   AUTOINCREMENT,
                      MSGDATE   DATE      NOT NULL,
                      POSTER    TEXT      NOT NULL,
                      CONTENT   TEXT      NOT NULL,
                      POSTID    INTEGER   NOT NULL,
                      FOREIGN KEY(POSTID) REFERENCES POST(POSTID)
                      FOREIGN KEY(POSTER) REFERENCES USER(USERNAME));
COMMIT;
